name: workshop_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.16.0           # Possui mais funcoes e classes que funcionam com listas
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1                # Implementacao de um estilo de retorno diferente (Either)
  ds_podi:                      # Design System do Podi
    git:
      url: https://github.com/podiapp/ds_podi.git
      ref: main
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4          # Gerenciador de estado
  flutter_modular: ^5.0.3       # Modulos para o Flutter
  flutter_styled_toast: ^2.1.3  # Toasts (snackbars) mais personalizaveis
  flutter_svg: ^1.1.6           # Conseguir inserir SVGs (extensao) para 
  intl: ^0.17.0                 # Disponibiliza internacionalizacao para o aplicativo
  mobx: 2.0.7+2                 # Gerenciador de estado

dev_dependencies:
  build_runner: any             # Gera novos codigos automaticamente
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: any
  modular_codegen: any

flutter:
  uses-material-design: true